---
deployment:
  tasks:
    - export DEPLOYPATH=/home/etnicode/public_html
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R route $DEPLOYPATH

    # - /bin/cp index.html $DEPLOYPATH
